language: groovy
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - chmod +x ./gradlew

script:
  - ./gradlew --no-daemon assemble

script:
  - ./gradlew --no-daemon check
